spring.application.name=smartpark
server.port=${PORT:8080}

app.bank.account=0707561652
app.bank.owner=NGUYEN THANH HUY
app.bank.name=MB

spring.datasource.url=jdbc:h2:file:./data/smartparkdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vovietnhat1996@gmail.com
spring.mail.password=gvofejaenxpsylmo

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.security.user.name=disable
spring.security.user.password=disable

spring.thymeleaf.cache=false

logging.level.org.thymeleaf=DEBUG
logging.file.name=smartpark/app.log
